# Gunakan image node dengan versi yang sesuai
FROM node:22.11.0

# Set direktori kerja di dalam container
WORKDIR /usr/src/app

# Salin file package.json dan package-lock.json ke dalam container
COPY package*.json ./

# Install dependencies
RUN npm install

# Salin seluruh kode aplikasi ke dalam container, kecuali node_modules
COPY . .

# Build TypeScript
RUN npm run build

# Expose port sesuai dengan PORT yang ada di .env
EXPOSE 3000

# Perintah untuk menjalankan aplikasi
CMD ["npm", "start"]
